### ISSUE TITLE
Crash after upgrading from 4.13.22 to 4.14.0

### ISSUE THREAD

**Issue by reporter4u** [globaleaks/GlobaLeaks#3919]
### What version of GlobaLeaks are you using?

4.13.22 --> 4.14.0

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

After upgrading from 4.13.22 to 4.14.0 Globaleaks log reports 'Server Shut Down' and the service is non more working.

```
[...]
2024-01-02 10:13:05+0100 [-] [I]  * User table migrated (8 entry(s))
2024-01-02 10:13:05+0100 [-] [I]  * WhistleblowerFile table migrated (14 entry(s))
2024-01-02 10:13:06+0100 [-] [E] Failure: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Field.step_id has an attribute 'is_not'
2024-01-02 10:13:06+0100 [-] [E] Verbose exception traceback:
2024-01-02 10:13:06+0100 [-] [I] Traceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 747, in __getattr__\n    return getattr(self.comparator, key)\n\nAttributeError: 'Comparator' object has no attribute 'is_not'\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/attributes.py", line 236, in __getattr__\n    return getattr(self.comparator, key)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 987, in __getattr__\n    return self._fallback_getattr(key)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/properties.py", line 364, in _fallback_getattr\n    return getattr(self.__clause_element__(), key)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 749, in __getattr__\n    util.raise_(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_\n    raise exception\n\nAttributeError: Neither 'AnnotatedColumn' object nor 'Comparator' object has an attribute 'is_not'\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/db/__init__.py", line 94, in update_db\n    migration.perform_migration(db_version)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/db/migration.py", line 280, in perform_migration\n    perform_data_update(new_db_file)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/db/migration.py", line 157, in perform_data_update\n    db_load_defaults(session)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/db/appdata.py", line 150, in db_load_defaults\n    db_fix_orphans_models(session)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/db/appdata.py", line 133, in db_fix_orphans_models\n    session.query(models.Field).filter(models.Field.instance == 0, models.Field.step_id.is_not(None), not_(models.Field.step_id.in_(steps_ids))).delete(synchronize_session=False)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/attributes.py", line 238, in __getattr__\n    util.raise_(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_\n    raise exception\n\nAttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Field.step_id has an attribute 'is_not'\n
2024-01-02 10:13:06+0100 [-] Server Shut Down.
```

**Comment by evilaliv3** [comment]
Thank you @reporter4u 

the bug is confirmed but is not critical.
We are issuing a patch and we will be including it in a release 4.14.1; It will be sufficient for you to update to this release to fix the situation.
